[book]
authors = ["zhaosz"]
language = "en"

src = "src"
title = "spring"

# https://doc.rust-lang.org/cargo/getting-started/installation.html
# cargo install mdbook
# cargo install mdbook-epub
[output.html]
